Fix: use dash

diff --git a/.github/workflows/secrets-test.yml b/.github/workflows/secrets-test.yml
--- a/.github/workflows/secrets-test.yml
+++ b/.github/workflows/secrets-test.yml
@@ -6,11 +6,11 @@ on:
 jobs:
   main-job:
     steps:
-      name: first-step
-      run: |
-        if [[ ${{ "secrets.SUPER_SECRET" -eq 15 }}]]; then
-          echo 'SUCCESS'
-        else
-          echo 'FAIL'
-          exit 1
-        fi
+      - name: first-step
+        run: |
+          if [[ ${{ "secrets.SUPER_SECRET" -eq 15 }}]]; then
+            echo 'SUCCESS'
+          else
+            echo 'FAIL'
+            exit 1
+          fi
